### ISSUE TITLE
update setup.py to limit fastKDE version - API breaking changes coming

### ISSUE THREAD

**Issue by taobrienlbl** [NinelK/CopulaGP#16]
API-breaking changes are coming to fastkde (see [this PR](https://github.com/LBL-EESA/fastkde/pull/26)).  I see that `setup.py` has fastKDE listed without an upper limit on the version.  I suggest changing this to `fastkde==1.0.30` (or limiting to <2.*) to ensure that code dependent on fastKDE continues to work.

Neat looking package, btw!  I look forward to reading about it.

**Comment by NinelK** [comment]
Thank you very much for the suggestion. I tested this version and fixed it in the requirements.

I hope our package will be useful for you! Let me know if you have questions.
